### ISSUE TITLE
Ipswich scraper seems to miss DAs around the end of the month

### ISSUE THREAD

**Issue by katska** [planningalerts-scrapers/ipswich#1]
Someone would like to post a submission for a DA thats up on Ipswich council, but it's not on planningalerts.org.au - other DAs are showing up from Ipswich. CA-6770 / 2018 

Searching http://pdonline.ipswich.qld.gov.au/  for 6770 / 2018 returns the DA for 196 - 198 and adjacent addresses on Jones Road, Bellbird Park- which is to turn 4 lots into 47 

(added by James) This seems to be happening because the DA was filed near the end of the month; the scraper only looks at "This month" so it can miss things added near the end of the month.

#4 tracks the broader issue of other bugs which are also affecing this DA

**Comment by benrfairless** [comment]
Suspect the cause of this is the scraper is checking for monthly when it should be checking for yearly. I can set it up to pull the last year's worth of requests in there, but I'm not sure what a good idea this would be.

**Comment by jamezpolley** [comment]
[6770/2018](http://pdonline.ipswich.qld.gov.au/pdonline/Modules/ApplicationMaster/default.aspx?page=wrapper&key=742312) is dated on the 30th of the month.

We've seen issues with other scrapers that use "this month" before; it seems that there can be cases around the end of the month when applications get missed. I suspect this may be because the documents were submitted on the 30th and are shown as such, but weren't visible on the website until the 1st or 2nd of the next month. As we only search for "this month", that means we won't see them.

We've been able to change other scrapers to search for the last N days instead, and found that this seems to work better. In this case, an example of a search for a particular range of days is:

http://pdonline.ipswich.qld.gov.au/pdonline/Modules/ApplicationMaster/default.aspx?page=found&1=22/10/2018&2=28/10/2018&3=&4=&4a=&6=F&8=&11=&12=&13=&14=&15=&21=&22=&7=

**Comment by LoveMyData** [comment]
Changed default from this month to past 14 days. Also added support for data recovery.

However, data recovery option will not be fully functional until #3 is fixed.

**Comment by katska** [comment]
The missing DA is still not in planningalerts -  @jamezpolley please reopen? (not an option I can see available to me)

**Comment by jamezpolley** [comment]
Actually, I think it's cleaner to leave this issue closed; I've edited the original message to make this issue more clearly about the end-of-the-month issue.

I've raised #4  to act as a master issue for tracking all the bugs that prevent us from getting this DA on the site.
